name: ride_on
description: "RideOn is a smart and reliable taxi booking app built for your daily travel needs. With trusted drivers, quick pickups, ride history, and 24/7 customer support, Zup makes every journey smooth and stress-free."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter 

  cupertino_icons: ^1.0.6
  flutter_bloc: ^9.0.0
  provider: ^6.1.2
  flutter_screenutil: ^5.9.3
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  flutter_svg: ^2.0.17
  google_fonts: ^6.2.1
  intl_phone_field: ^3.2.0
  google_maps_flutter: ^2.10.0
  firebase_auth: ^5.5.2
  firebase_core: ^3.12.1
  firebase_messaging: ^15.2.4
  firebase_database: ^11.3.4
  cloud_firestore: ^5.6.6
  google_places_flutter: ^2.0.9
  geocoding: ^3.0.0
  location: ^5.0.3
  flutter_rating_bar: ^4.0.1
  equatable: ^2.0.7
  bot_toast: ^4.1.3
  google_sign_in: ^6.2.2
  shimmer: ^3.0.0
  geolocator: ^13.0.2
  image_picker: ^1.1.2
  flutter_polyline_points: ^2.1.0
  flutter_image_compress: ^2.4.0
  intl: ^0.20.2
  pull_to_refresh: ^2.0.0
  flutter_html: any
  geoflutterfire_plus: ^0.0.24
  flutter_inappwebview: ^6.1.5
  lottie: ^3.3.1
  onesignal_flutter: ^5.3.3
  flutter_local_notifications: ^17.2.2
  sign_in_with_apple: ^6.1.1




dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/appicons.png"
  image_path_ios: "assets/images/appicons.png"


flutter:


  uses-material-design: true


  assets:
    - assets/images/
    - assets/language/
    - assets/json/
    - assets/fonts/

  fonts:
    - family: Poppins Black
      fonts:
        - asset: assets/fonts/Poppins-Black.ttf
    - family: Poppins Bold
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
    - family: Poppins Medium
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
    - family: Poppins Regular
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
    - family: Poppins Light
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
    - family: Poppins SemiBold
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.ttf
    - family: Poppins ExtraBold
      fonts:
        - asset: assets/fonts/Poppins-ExtraBold.ttf
    - family:  Poppins Thin
      fonts:
        - asset: assets/fonts/Poppins-Thin.ttf

  